symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    lifetime: 3600
    throttle_limit: 3600
    #handles expired reset password requests that may have been left in persistence.
    enable_garbage_collection: true